export function schemaForCategory(category='', productName='') {
  const n = `${category} ${productName}`.toLowerCase();
  if (/manual vacuum extractor|vacuum extractor|obstetric vacuum/.test(n)) return ['Product Name','Type','Brand','Model','Vacuum Pressure','Material','Operation','Application','Construction','Usage','Design','Country of Origin'];
  if (/rubber processing|rubber roller sheeting|rubber sheeting|two roll rubber|mixing mill/.test(n)) return ['Product Name','Brand','Model','Product Type','Roller Material','Roller Size','Working Width','Roller Speed','Drive Type','Motor Power','Roll Gap Adjustment','Machine Construction','Voltage','Safety Features','Application'];
  if (/breath alcohol|alcohol analyzer|alcohol analyser|breathalyzer|breathalyser/.test(n)) return ['Product Name','Brand','Model','Product Type','Measurement','Sensor Technology','Sampling Method','Display','Measurement Units','Power Supply','Alarm','Mouthpiece','Data Memory','Operating Environment','Application'];
  if (/lux meter|illuminance|light meter/.test(n)) return ['Product Name','Brand','Model','Measuring Range','Resolution','Accuracy','Display','Sensor','Range Selection','Measurement Units','Sampling Rate','Data Logging','Functions','Interface','Power Supply','Auto Power Off','Low Battery Indication','Operating Temperature','Standard Accessories'];
  if (/oscilloscope|scope meter|scopemeter/.test(n)) return ['Product Name','Brand','Model','Bandwidth','Number of Channels','Sampling Rate','Memory Depth','Vertical Resolution','Rise Time','Display','Trigger','Interface','Probe','Power'];
  if (/analytical balance|precision balance/.test(n)) return ['Product Name','Brand','Series','Model','Capacity','Readability','Repeatability','Linearity','Minimum Weight','Pan Size','Calibration','Stabilization','Display','Draft Shield','Communication','Operating Temperature','Power'];
  if (/skinfold/.test(n)) return ['Product Name','Brand','Model','Usage / Application','Country of Origin','Bearing Components','Measuring Range','Measuring Pressure','Accuracy','Dial Graduation','Repeatability','Construction'];
  if (/uv meter|ultraviolet/.test(n)) return ['Product Name','Brand','Model','UV Band','Spectral Range','Measurement Range','Resolution','Accuracy','Sensor','Display','Data Logging','Interface','Power','Operating Temperature','Standard Accessories'];
  if (/furnace/.test(n)) return ['Product Name','Brand','Model','Maximum Temperature','Working Temperature','Chamber Size','Heating Element','Temperature Controller','Accuracy','Power','Voltage','Construction','Insulation','Application'];
  if (/gas detector|gas analyser|gas analyzer/.test(n)) return ['Product Name','Brand','Model','Target Gas / Parameters','Sensor Technology','Measuring Range','Resolution','Accuracy','Alarm','Sampling Method','Display','Data Logging','Communication','Power','Ingress Protection','Application'];
  if (/temperature calibrator|temperature calibration/.test(n)) return ['Product Name','Brand','Model','Input / Output Type','Temperature Range','Accuracy','Resolution','Sensor / Thermocouple Types','RTD Support','Display','Communication','Power','Application'];
  if (/data logger|datalogger/.test(n)) return ['Product Name','Brand','Model','Measured Parameters','Channels','Input Type','Logging Interval','Memory','Display','Communication','Software','Power','Operating Environment','Application'];
  if (/microscope/.test(n)) return ['Product Name','Brand','Model','Microscope Type','Magnification','Objective / Lens','Display / Eyepiece','Illumination','Camera','Working Distance','Interface','Power','Application'];
  if (/digital manometer.*(?:air\s*flow|airflow|flow)|(?:air\s*flow|airflow|flow).*digital manometer|differential pressure.*(?:air\s*flow|airflow)/.test(n)) return ['Product Name','Brand','Model','Measurement Type','Differential Pressure Range','Gauge Pressure Range','Accuracy','Resolution','Pressure Units','Airflow / Velocity Range','Flow Calculation','Pitot Tube / Probe Compatibility','Duct Area Input','Display','Data Hold','Min / Max / Average','Data Logging','Interface','Power Supply','Operating Temperature','Standard Accessories','Application'];
  if (/digital manometer|differential manometer|manometer/.test(n)) return ['Product Name','Brand','Model','Measurement Type','Pressure Range','Accuracy','Resolution','Pressure Units','Overpressure','Port / Connection','Display','Data Hold','Min / Max','Data Logging','Interface','Power Supply','Operating Temperature','Standard Accessories','Application'];
  if (/pressure gauge|pressure meter/.test(n)) return ['Product Name','Brand','Model','Pressure Range','Accuracy','Resolution','Pressure Units','Process Connection','Display','Overpressure','Media Compatibility','Power','Application'];
  if (/caliper|vernier/.test(n)) return ['Product Name','Brand','Model','Caliper Type','Measuring Range','Resolution','Accuracy','Jaw Type','Display','Output','Material','Application'];
  if (/flow meter|flowmeter/.test(n)) return ['Product Name','Brand','Model','Medium','Flow Range','Accuracy','Repeatability','Connection','Output','Pressure','Temperature','Display','Power'];
  if (/refractometer|brix meter|brix refract/.test(n)) return ['Product Name','Brand','Model','Measurement Parameter','Measurement Range (Brix)','Resolution','Accuracy','Temperature Range','Temperature Compensation','Sample Volume','Measurement Time','Display','Ingress Protection','Power Supply','Dimensions','Weight','Catalog No.','Application'];
  if (/freeze dryer|freeze drying|lyophili[sz]er|lyophili[sz]ation/.test(n)) return ['Product Name','Brand','Model','Product Type','Application','Condenser Temperature','Ice Condenser Capacity','Drying Capacity','Vacuum Level','Shelf Area','Shelf Temperature','Number of Shelves','Chamber Type','Refrigeration System','Vacuum Pump','Control System','Display','Power Supply','Construction'];
  if (/karl fischer|karl fisher|kf titrator/.test(n)) return ['Product Name','Brand','Model','Titration Type','Moisture Range','Resolution','Accuracy / Repeatability','Titrant / Reagent System','Sample Introduction','Endpoint Detection','Burette Resolution','Display','Data Storage','Interfaces','Power Supply','Application'];
  if (/distillation/.test(n)) return ['Product Name','Brand','Model','Capacity','Glass Type','Flask Capacity','Condenser Type','Heating Method','Temperature Range','Number of Units','Power Requirement','Application','Standard Accessories'];
  if (/air quality|iaq/.test(n)) return ['Product Name','Brand','Model','Measured Parameters','PM2.5 Range','PM10 Range','CO₂ Range','VOC Range','Temperature','Humidity','Accuracy','Display','Data Logging','Communication','Power','Battery','Operating Environment'];
  if (/ph meter/.test(n)) return ['Product Name','Brand','Model','pH Range','Resolution','Accuracy','Calibration Points','Temperature Range','Temperature Compensation','Electrode','Display','Data Logging','Communication','Power'];
  if (/moisture/.test(n)) return ['Product Name','Brand','Model','Application / Material','Measuring Range','Resolution','Accuracy','Sensor / Probe','Display','Data Logging','Communication','Power'];
  if (/vibration/.test(n)) return ['Product Name','Brand','Model','Measurement Mode','Measuring Range','Frequency Range','Resolution','Accuracy','Sensor','Display','Data Logging','Communication','Power'];
  // Unknown categories intentionally get only identity hints. Gemini must determine
  // the technically relevant fields from the actual product instead of inheriting a
  // fixed measurement template.
  return ['Product Name','Brand','Model'];
}
